config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cvs.two:
      branch: main
      repo: https://github.com/cessda/cessda.cvs.two
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-gamboge-maltese.sh
        container: qc.acc_shabby-amethyst-flounder
  QC.Doc:
    repos:
      github.com/cessda/cessda.cvs.two find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-coral-pig.sh
        container: qc.doc_tacky-ivory-wolf
      github.com/cessda/cessda.cvs.two git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-sangria-heron.sh
        container: qc.doc_sleazy-emerald-impala
      github.com/cessda/cessda.cvs.two markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-wisteria-fox.sh
        container: qc.doc_thirsty-bistre-manatee
  QC.Lic:
    repos:
      github.com/cessda/cessda.cvs.two licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-red-quail.sh
        container: qc.lic_freaky-white-dachshund
  QC.Met:
    repos:
      github.com/cessda/cessda.cvs.two cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-bronze-dogfish.sh
        container: qc.met_pretty-persimmon-cattle
  QC.Sty:
    repos:
      github.com/cessda/cessda.cvs.two checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-buff-chinook.sh
        container: qc.sty_sloppy-pear-monkey
      github.com/cessda/cessda.cvs.two jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-periwinkle-fly.sh
        container: qc.sty_clammy-copper-llama
  QC.Ver:
    repos:
      github.com/cessda/cessda.cvs.two get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-corn-lobster.sh
        container: qc.ver_clammy-teal-dugong
timeout: 5400
